#include "MySBBST.h"
#include "student.hh"
using namespace std;

int main()
{
    cout << "Testing int tree" << endl;
    MySBBST<int, int, intintCompare, intintCompare> tree1(0);
    cout << "Test remove search and print for empty tree" << endl;
    cout << tree1.search(5) << "   " << tree1.remove(5) << endl;
    tree1.printout();
    cout << endl;
    cout << "RR Prob Check" << endl;
    tree1.add(1);
    tree1.add(2);
    tree1.add(3);
    tree1.printout();
    cout << endl << "LL Prob Check" << endl;
    MySBBST<int, int, intintCompare, intintCompare> tree2(0);
    tree2.add(3);
    tree2.add(2);
    tree2.add(1);
    tree2.printout();
    cout << endl << "LR Prob Check" << endl;
    MySBBST<int, int, intintCompare, intintCompare> tree3(0);
    tree3.add(4);
    tree3.add(2);
    tree3.add(3);
    tree3.printout();
    cout << endl << "RL Prob Check" << endl;
    MySBBST<int, int, intintCompare, intintCompare> tree4(0);
    tree4.add(1);
    tree4.add(3);
    tree4.add(2);
    tree4.printout();
    cout << endl << "Remove balance check" << endl;
    MySBBST<int, int, intintCompare, intintCompare> tree5(0);
    tree5.add(5);
    tree5.printout();
    cout << endl;
    tree5.add(6);
    tree5.printout();
    cout << endl;
    tree5.add(8);
    tree5.printout();
    cout << endl;
    tree5.add(3);
    tree5.printout();
    cout << endl;
    tree5.add(2);
    tree5.printout();
    cout << endl;
    tree5.add(4);
    tree5.printout();
    cout << endl;
    tree5.add(7);
    tree5.printout();
    cout << endl;
    tree5.remove(5);
    tree5.printout();
    cout << " Remove 5" << endl;
    tree5.remove(8);
    tree5.printout();
    cout << " Remove 8" << endl;
    tree5.remove(7);
    tree5.printout();
    cout << " Remove 7" << endl;
    cout << "Search test (3) and not in tree" << endl;
    cout << tree5.search(3) << endl;
    cout << tree5.search(100) << endl;
    cout << "Invalid input check add, remove, search" << endl;
    tree5.add(0);
    tree5.remove(0);
    tree5.search(0);
    cout << "Testing char tree" << endl;
    MySBBST<char, char, charcharCompare, charcharCompare> tree6(0);
    cout << "Test remove search and print for empty tree" << endl;
    cout << tree6.search('e') << "   " << tree6.remove('e') << endl;
    tree6.printout();
    cout << endl;
    cout << "RR Prob Check" << endl;
    tree6.add('a');
    tree6.add('b');
    tree6.add('c');
    tree6.printout();
    cout << endl << "LL Prob Check" << endl;
    MySBBST<char, char, charcharCompare, charcharCompare> tree7(0);
    tree7.add('c');
    tree7.add('b');
    tree7.add('a');
    tree7.printout();
    cout << endl << "LR Prob Check" << endl;
    MySBBST<char, char, charcharCompare, charcharCompare> tree8(0);
    tree8.add('d');
    tree8.add('b');
    tree8.add('c');
    tree8.printout();
    cout << endl << "RL Prob Check" << endl;
    MySBBST<char, char, charcharCompare, charcharCompare> tree9(0);
    tree9.add('a');
    tree9.add('c');
    tree9.add('b');
    tree9.printout();
    cout << endl << "Add and Remove balance check" << endl;
    MySBBST<char, char, charcharCompare, charcharCompare> tree10(0);
    tree10.add('e');
    tree10.printout();
    cout << endl;
    tree10.add('f');
    tree10.printout();
    cout << endl;
    tree10.add('h');
    tree10.printout();
    cout << endl;
    tree10.add('c');
    tree10.printout();
    cout << endl;
    tree10.add('b');
    tree10.printout();
    cout << endl;
    tree10.add('d');
    tree10.printout();
    cout << endl;
    tree10.add('g');
    tree10.printout();
    cout << endl;
    tree10.remove('e');
    tree10.printout();
    cout << " Remove e" << endl;
    tree10.remove('h');
    tree10.printout();
    cout << " Remove h" << endl;
    tree10.remove('g');
    tree10.printout();
    cout << " Remove g" << endl;
    cout << "Search test (c) and not in tree" << endl;
    cout << tree10.search('c') << endl;
    cout << tree10.search('z') << endl;
    cout << "Invalid input check add, remove, search" << endl;
    tree10.add(0);
    tree10.remove(0);
    tree10.search(0);
    cout << "Testing student tree" << endl;
    student s5("a", "a", 5);
    student s6("b", "b", 6);
    student s8("c", "c", 8);
    student s3("d", "d", 3);
    student s2("e", "e", 2);
    student s4("f", "f", 4);
    student s7("g", "g", 7);
    student zero;
    MySBBST<student, unsigned int, studentStudentComp, uintStudentComp> tree11(zero);
    cout << "Test remove search and print for empty tree" << endl;
    cout << tree11.search(5) << "   " << tree11.remove(5) << endl;
    tree11.printout();
    cout << endl;
    cout << "RR Prob Check" << endl;
    tree11.add(s2);
    tree11.add(s3);
    tree11.add(s4);
    tree11.printout();
    cout << endl << "LL Prob Check" << endl;
    MySBBST<student, unsigned int, studentStudentComp, uintStudentComp> tree12(zero);
    tree12.add(s4);
    tree12.add(s3);
    tree12.add(s2);
    tree12.printout();
    cout << endl << "LR Prob Check" << endl;
    MySBBST<student, unsigned int, studentStudentComp, uintStudentComp> tree13(zero);
    tree13.add(s4);
    tree13.add(s2);
    tree13.add(s3);
    tree13.printout();
    cout << endl << "RL Prob Check" << endl;
    MySBBST<student, unsigned int, studentStudentComp, uintStudentComp> tree14(zero);
    tree14.add(s2);
    tree14.add(s4);
    tree14.add(s3);
    tree14.printout();
    cout << endl << "Remove balance check" << endl;
    MySBBST<student, unsigned int, studentStudentComp, uintStudentComp> tree15(zero);
    tree15.add(s5);
    tree15.printout();
    cout << endl;
    tree15.add(s6);
    tree15.printout();
    cout << endl;
    tree15.add(s8);
    tree15.printout();
    cout << endl;
    tree15.add(s3);
    tree15.printout();
    cout << endl;
    tree15.add(s2);
    tree15.printout();
    cout << endl;
    tree15.add(s4);
    tree15.printout();
    cout << endl;
    tree15.add(s7);
    tree15.printout();
    cout << endl;
    tree15.remove(5);
    tree15.printout();
    cout << " Remove s5" << endl;
    tree15.remove(8);
    tree15.printout();
    cout << " Remove s8" << endl;
    tree15.remove(7);
    tree15.printout();
    cout << " Remove s7" << endl;
    cout << "Search test (3) and not in tree" << endl;
    cout << tree15.search(3) << endl;
    cout << tree15.search(5) << endl;
    cout << "Invalid input check add, remove, search" << endl;
    tree5.add(0);
    tree5.remove(0);
    tree5.search(0);
}
